-- MySQL Script generated by MySQL Workbench
-- Fri Jan  3 14:47:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tw_user_center
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tw_user_center
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tw_user_center` DEFAULT CHARACTER SET utf8 ;
USE `tw_user_center` ;

-- -----------------------------------------------------
-- Table `tw_user_center`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tw_user_center`.`user` (
  `pk_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL COMMENT '用户名',
  `password` VARCHAR(45) NOT NULL COMMENT '密码',
  `phone` VARCHAR(45) NULL COMMENT '手机号',
  `email` VARCHAR(45) NULL COMMENT '邮箱',
  `wx_name` VARCHAR(100) NULL COMMENT '微信名称\n',
  `gender` TINYINT(1) NULL COMMENT '性别',
  `avatar` VARCHAR(500) NULL COMMENT '头像',
  `role` INT NULL COMMENT '角色',
  `position` VARCHAR(45) NULL COMMENT '职位',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`pk_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tw_user_center`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tw_user_center`.`team` (
  `pk_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `team_name` VARCHAR(45) NOT NULL,
  `team_description` VARCHAR(200) NULL COMMENT '团队描述',
  `team_creator_id` INT UNSIGNED NOT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`pk_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tw_user_center`.`user_team_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tw_user_center`.`user_team_relation` (
  `pk_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `team_id` INT UNSIGNED NOT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`pk_id`),
  INDEX `fk_user_team_user_idx` (`user_id` ASC),
  INDEX `fk_user_team_team1_idx` (`team_id` ASC),
  CONSTRAINT `fk_user_team_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `tw_user_center`.`user` (`pk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_team_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `tw_user_center`.`team` (`pk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tw_user_center`.`messageRequestDTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tw_user_center`.`messageRequestDTO` (
  `pk_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL COMMENT '标题\n',
  `content` VARCHAR(500) NOT NULL COMMENT '内容',
  `sender_id` INT UNSIGNED NOT NULL COMMENT '发送者id',
  `sender_role` INT NOT NULL COMMENT '发送者角色',
  `receiver_id` INT UNSIGNED NOT NULL COMMENT '接受者id',
  `type` INT NOT NULL COMMENT '消息类型',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`pk_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tw_user_center`.`user_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tw_user_center`.`user_message` (
  `pk_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `message_id` INT UNSIGNED NOT NULL,
  `status` INT NOT NULL COMMENT '消息状态\n0:未读\n1:已读',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`pk_id`),
  INDEX `fk_user_message_user1_idx` (`user_id` ASC),
  INDEX `fk_user_message_message1_idx` (`message_id` ASC),
  CONSTRAINT `fk_user_message_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tw_user_center`.`user` (`pk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_message_message1`
    FOREIGN KEY (`message_id`)
    REFERENCES `tw_user_center`.`messageRequestDTO` (`pk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
