spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tw_user_center?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: jmr980328
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #        namespace: 0e5a522d-9b74-4833-af36-35297b3e50fb
  #        cluster-name: NJ
  application:
    name: user-center
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8081
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: user-group

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true #pageSize=0

aliyun:
  accessKeyId: LTAI4Fsk3ufKP5w3LN61QHhp
  accessKeySecret: zAGppLb9O9FWCaGCYi2Bl76sGGZw1T
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucketName: team-work
    urlPrefix: http://oss.jinminrui.cn/
